# Generated by Django 3.2.6 on 2021-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=10000)),
                ('price_first', models.CharField(max_length=1000)),
                ('price_second', models.CharField(max_length=1000)),
                ('link_photo', models.CharField(max_length=1000)),
                ('main', models.CharField(max_length=1000)),
                ('id_goods', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
