# Generated by Django 3.2.6 on 2021-08-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.TextField(blank=True, null=True)),
                ('date_msg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_msg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsGoods',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=10000)),
                ('price_first', models.CharField(max_length=1000)),
                ('price_second', models.CharField(max_length=1000)),
                ('link_photo', models.CharField(max_length=1000)),
                ('main', models.CharField(max_length=1000)),
                ('id_goods', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'polls_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=1000000000, primary_key=True, serialize=False)),
                ('phone', models.TextField(blank=True, null=True)),
                ('fio', models.TextField(blank=True, db_column='FIO', null=True)),
                ('nova_poshta', models.TextField(blank=True, null=True)),
                ('adrees', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('last_zakaz', models.TextField(blank=True, null=True)),
                ('promo_profile', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.CharField(max_length=1000000000, primary_key=True, serialize=False)),
                ('notification', models.TextField(blank=True, null=True)),
                ('notifical_day', models.TextField(blank=True, null=True)),
                ('promo', models.TextField(blank=True, null=True)),
                ('promo_day', models.IntegerField(blank=True, null=True)),
                ('promo_date', models.TextField(blank=True, null=True)),
                ('salse_promo', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.CharField(max_length=1000000000)),
                ('grind', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, db_column='Weight', null=True)),
                ('quantity', models.TextField(blank=True, db_column='Quantity', null=True)),
                ('orderr', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('id_coffe', models.IntegerField(blank=True, null=True)),
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('basket', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('promo', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'zakaz',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'managed': False},
        ),
    ]
